# Generated by Django 4.0.5 on 2022-07-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=70)),
                ('mono', models.IntegerField()),
                ('pin', models.IntegerField()),
                ('pas', models.CharField(max_length=70)),
            ],
        ),
    ]
